version: '3'

services:
  database:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: tickpass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - tickpass-db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  tickpass-db:
