#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_ticket_validator_index:
  path: /
  controller: App\Controller\TicketValidatorController::index

app_ticket_validator_check:
  path: /validation
  controller: App\Controller\TicketValidatorController::checkSerial
  methods: POST
